### ISSUE TITLE
Add (or document) logging

### ISSUE THREAD

**Issue by mileswwatkins** [jamesturk/spatula#2]
It'd be helpful to know how to integrate with multi-level logging via `self.…`. I can't find any examples of logging in the ~6 Spatula–Pupa modules in Open States at the moment.

**Comment by jamesturk** [comment]
Going to consider this out of scope, spatula is just a way to write scrapers, the existing logging mechanisms (import logging) work fine w/ it.

I think the confusion comes b/c scrapelib exposes logging, which a lot of the scrapers then use- that's still possible but is a scrapelib feature for weird legacy reasons (it being pulled out of the originally openstates repo), not something a library *should* provide.
