### ISSUE TITLE
docs links broken in README.md

### ISSUE THREAD

**Issue by lo5an** [jamesturk/spatula#21]
spatula looks great! I'm recommending that some coworkers look at it for a project. 

I noticed a small docs issue. Since `README.md` is a link to `docs/index.md`, relative links to the other pages in the `docs` folder are broken when accessed from `README.md` as displayed on the spatula GitHub repo's main page.

**Comment by jamesturk** [comment]
thanks!  I'll take a look & see if there are any clever options or if I just need to split the README from index.md
