### ISSUE TITLE
Retries - Bad Pattern

### ISSUE THREAD

**Issue by styledev** [jamesturk/spatula#35]
**Describe the bug**
The example code on https://jamesturk.github.io/spatula/advanced-techniques/#retries for Retries does not work.
spatula test RejectPartialPage(source=URL("https://openstates.org", retries=3))
zsh: bad pattern: RejectPartialPage(source=URL(https://openstates.org, retries=3))

**Environment**
MacOS Montery
Python 3.10.7
spatula, version 0.9.0

**Comment by jamesturk** [comment]
Hi! `RejectPartialPage(source=URL("https://openstates.org/", retries=3))` is Python code, not meant to be on the command line.
