### ISSUE TITLE
lxml is limited to 4.X

### ISSUE THREAD

**Issue by showerst** [jamesturk/spatula#39]
**Describe the bug**
lxml is limited to ```lxml = "^4.6.2"``` in pyproject.toml, but there's a 5.X series now

I want to add some other libraries in openstates that require lxml 5.X, @jamesturk would you mind rolling a new release with 5.x support? 

Thanks!
-Tim

**Comment by jamesturk** [comment]
of course, just pushed 0.9.1, lmk if there are any issues!
